### ISSUE TITLE
Should ManagedSpan become ManagedSpanContext?

### ISSUE THREAD

**Issue by sjoerdtalsma** [opentracing-contrib/java-spanmanager#5]
As @bensigelman pointed out, a `Span` behaviour is undefined after it is finished, but its `SpanContext` remains valid.

Would we lose any crucial functionality by switching to `ManagedSpanContext` instead of `Span`?
I know our tracing code that uses the current concept can be adapted relatively easy.

However, since this change potentially has massive impact, I'd suggest getting it over with sooner rather than later before there is no way back.

@adriancole @wu-sheng @yurishkuro I would love to hear your thoughts on this!

**Comment by sjoerdtalsma** [comment]
I think I'll start working on a PR for this either way to keep momentum going.

**Comment by bhs** [comment]
There will certainly be some loss of functionality (adding tags / logs to the active span without a preexisting reference)... I just think that's a fine price to pay in exchange for the elimination of a nasty race and generalization of span-starting overall.

**Comment by objectiser** [comment]
There seems to be three use cases - possibly we can think of a mechanism that could help with them all:

1) To establish a reference for a newly created span - this reference currently could either be ChildOf or FollowsFrom depending upon whether the referenced span has finished. Obtaining span or span context from the span manager would not provide this information - so possibly the span manager needs to provide some additional knowledge that can be used when adding the reference to the child span.

2) To enrich the current span - only relevant when the span is 'active'. I believe this is important if we have information that needs to be added during or at the end of the span (i.e. logs, tags such as `http.status_code`).

3) To `finish` the current span - again only relevant if the span is 'active', but necessary if starting and finishing a span are performed (for example) in separate callbacks.

**Comment by objectiser** [comment]
@sjoerdtalsma @bensigelman How about providing a mechanism on the `SpanManager` (which could eventually move to Tracer?) to retrieve an active `Span` from its `SpanContext` - so returns null if not active. The `SpanManager` could just deal with `SpanContext`, but it would provide a way to deal with the three cases above.

**Comment by sjoerdtalsma** [comment]
@objectiser I have learned that it is probably best to keep the scope of the `SpanManager` or `SpanContextManager` as small as possible.
Initially I tried to solve many concerns in one library, but this led to huge discussions on where to go (https://github.com/opentracing-contrib/java-globaltracer/pull/1 got 185 comments!)
Therefore I think _starting / finishing_ of spans should preferably be kept separate from _managing / releasing_ them.

Let's try to keep this discussion limited to managing `Span` vs `SpanContext`. Do you have a pressing use-case that would not work with `ManagedSpanContext`?

**Comment by objectiser** [comment]
@sjoerdtalsma No pressing use-case currently. Would be good if could obtain span from context though, but that is more a spec question.

**Comment by yurishkuro** [comment]
@sjoerdtalsma I seem to be missing the rationale for this. Why not just manage the span? It's especially useful if you try to integrate logging, e.g. letting the code use the standard logging API (e.g. slf4j) which behind the scenes directs the logs into the current span.

**Comment by sjoerdtalsma** [comment]
@yurishkuro That would seem valid reasons for either managing the `Span`, or making the `SpanContext` richer.

I think another compelling reason is closing an active span where the span is not explicitly passed all the way through the code path and processing is split up between creation and closing (e.g. most async frameworks).

Just inviting everybody's opinion on this..

**Comment by yurishkuro** [comment]
> or making the SpanContext richer.

if by that you mean getting access to Span from SpanContext, as was mentioned above, then I fail to see the point of not storing Span to begin with. SpanContext is not meant to know about its span.

> I think another compelling reason is closing an active span where the span is not explicitly passed all the way through the code path and processing is split up between creation and closing (e.g. most async frameworks).

I'd be careful with that, we've been bitten by it. Personally my preference is to use framework's native means (some form of context) to pass server-side span from in-interceptor to out-interceptor. But some frameworks do not provide anything such context, and then the thread-local active span is the only solution (with the usual caveat that it's very easy to screw up thread local in async frameworks).

**Comment by objectiser** [comment]
@sjoerdtalsma @bensigelman @yurishkuro 

At the risk of making the discussion more complex, rather than deciding whether `Span` or `SpanContext` is better, we could consider the issue from a different level of abstraction.

If we had a concept such as `Conversation` (name not important) which represented the stack of active `Span`s for the **current thread** (of control). Rather than propagating spans, we instead propagate conversations - so a conversation is only owned by a single thread at a time.

The `Conversation` can provide access to the current active span - allowing additional tags/logs to be defined. If handling a request asynchronously, the complete conversation would be propagated between threads.

Where additional threads are used to perform work (e.g. concurrently) on behalf of the `Conversation`, a conversation reference (which is essentially just a `SpanContext`) would be passed - thus avoiding the issue of multiple threads trying to access/modify a span - only the thread owning the conversation would be able to modify and affect the lifecycle of the spans.

The executors propagating the ref could optionally implicitly start a child span to scope the work performed in the executed thread, providing an active span (conversation) upon which logs etc could be recorded.

**Comment by wu-sheng** [comment]
@objectiser we have a similar concept, in my company APM product, named `transaction`, which has the `can provide access to the current active span - allowing additional tags/logs to be defined`, and `represented the stack of active Spans for the current thread`

But, we don't propagation it, because there will be multi-threads to handle it, I think this is a bad situation. As you said:
>thus avoiding the issue of multiple threads trying to access/modify a span - only the thread owning the conversation would be able to modify and affect the lifecycle of the spans.

I think it belongs to only one thread, it's not possible all the time. Thread-A calls Thread-B, and you propagation `conversation` from A to B, sometimes, Thread-A will not wait Thread-B, and trace in-Thread-A will continue. How can you handle this?

**Comment by objectiser** [comment]
@wu-sheng This is where the nature of the relationship between Thread-A and Thread-B is important. If the `conversation` is being passed from A to B, then A should no longer have access to that converation. Thread-B will be the new **owner** of that conversation and be able to access/modify the current active span associated with it.

If the relationship between Thread-A and Thread-B is delegating some work on behalf of Thread-A to B, but A still retains control over the conversation, then the *conversation reference* (i.e. span context) would be passed to Thread-B instead. Whether Thread-B then creates a *ChildOf* or *FollowsFrom* reference would dependent on other factors.

**Comment by wu-sheng** [comment]
@sjoerdtalsma I think `SpanContext` and `Span` have different purpose, when you propagation, only `SpanContext` is your concern, `Span` is about this rpc invocation or something like this.

>or making the SpanContext richer.

-1 on this, it's not a good idea. This will mix `SpanContext` and `Span`.

**Comment by wu-sheng** [comment]
@objectiser , clearly, you have your mechanism to propagation span-context, rather than conversion. Why do you need to propagation conversion? Not propagation span-context all the time? I thought it is good enough.

In order to choose your propagation ways, you must know the thread-model, from a tracer developer side, or need to explain the diff to users, I did not see the advantage.

Can you tell me more about your tracer implementation?

**Comment by objectiser** [comment]
@wu-sheng This is not based on existing approach - just trying to think of a more general way to solve various issues.

As has been mentioned above, the benefit of having access to the span is being able to add logs/tags. The body of the work performed within the scope of a span may not be in the same thread that started the span - just to provide a simple example:

```
  public void doGet(HttpServletRequest request, HttpServletResponse response) {
      final AsyncContext acontext = request.startAsync();
      acontext.start(new Runnable() {
         public void run() {
            // Logging - where would it go?
            HttpServletResponse response = acontext.getResponse();
            ……
            // How would HTTP status code be associated with current span?
            acontext.complete();
   }
```

The `http.status_code` could be associated, if the framework can retain the `Span` as part of its local context (as mentioned by @yurishkuro ) but may not always be possible. It may cause problems in something like Camel, where the context is passed through complete flow, so means it would be necessary to maintain its own stack of `Span`s (I believe - still to investigate further).

**Comment by wu-sheng** [comment]
@objectiser I see, thank you for your explanation. 👍

**Comment by objectiser** [comment]
@wu-sheng no problem - although my suggestion would still have problems if the code tried to (for example) log a message at the end of the `doGet` method, as the `conversation` would have been transferred.

**Comment by wu-sheng** [comment]
@objectiser , yes, it's true. I think avoid all situations, on coding level, is not unrealistic. It's more likely a development guide. 

In that scene, you mentioned, if call `span.log` after transferred, as a tracer, you only can `throw exception`, `do nothing, just return` or `still log, facing multi-thread issue`. You can't forbid using `span` object in code-level.

---

BTW. In my experience, all APM/tracer user, if they need use sdk (not auto-instrumentation), I think they must know concepts, like span, trace, context, etc. And know how to propagation context between thread and cross-process, how to start/finish span. Because of this, nearly, all commercia-APM-products in China are using auto-instrumentation. OpenTracing Spec (all members) should help people understand these concepts. 

**Not only easy to understand/use for experts, but for rookies. Keep OT spec SDK as simple as possible. (Not include contrib-lib, like this one)** @bensigelman

**Comment by sjoerdtalsma** [comment]
Maybe the Span api should have an `isFinished()` method?
I think managing `Span` over `SpanContext` isn't actually bad, but you should know whether you can actually do things with the span or it already finished and basically became a `SpanContext` container?

**Comment by bhs** [comment]
There are three reasons to thread Span or SpanContext through a la SpanManager:

1. Make it easy to start a span ~anywhere without having a local var referring to a parent SpanContext [only need to manage a SpanContext for this, obviously]
1. Make it easy to log to / tag / otherwise reference the current Span without having a local var referring to it [one must manage a Span for this, also obviously]
1. *Knowing when to call `finish()` in the first place*

For Dapper in C++ (note that this doesn't make nearly as much sense in Java), it was this final reason that pushed SpanContext (actually called "TraceContext" at Google, but that is not important here) into this role rather than Span... the SpanContext was reference-counted, and when the final reference dropped the Span was finished implicitly. In fact, that was the only way to finish the Span.

This was really elegant in some cases. It was also kind of a bug farm. In my defense, I didn't come up with the idea... but I wish I had killed it :)

Anyway, I am still forming my own opinion about how to resolve all of these interrelated concerns (esp about the core OT APIs), but my leaning du jour is to pass a `Span` instance around and have a hook to remove it from any Manager and/or thread-local storage when a `Span` is finished.

**Comment by sjoerdtalsma** [comment]
> Anyway, I am still forming my own opinion about how to resolve all of these interrelated concerns (esp about the core OT APIs), but my leaning du jour is to pass a Span instance around and have a hook to remove it from any Manager and/or thread-local storage when a Span is finished.

+1

**Comment by sjoerdtalsma** [comment]
Closing this for now.

It is probabaly more important to gain experience with the `SpanManager` from real end-user experience, so there is merit to keeping the lib stable for now.
Besides, this discussion will almost certainly be repeated again in the standardisation effort to bring in-process propagation into the spec (https://github.com/opentracing/specification/issues/23).
